# Jekyll settings
defaults:
  -
    scope:
      path: working-on/sliding-nav/
    values:
      css:
        - /working-on/sliding-nav/layered-theme-menu-mr-tp.css
        - https://use.fontawesome.com/releases/v5.6.3/css/all.css
      layout: without-h1
      lang: en
      nomenu: true
      pageclass: cnt-wdth-lmtd

plugins:
  - jekyll-remote-theme

remote_theme: wet-boew/gcweb-jekyll